spring:
  data:
    elasticsearch:
      cluster-name: my-application
      #节点的地址 注意api模式下端口号是9300，千万不要写成9200
      cluster-nodes: 111.230.222.169:9300
  datasource:
    name: search
    url: jdbc:mysql://111.230.222.169:3306/test
    username: root
    password: plpl1234
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000

mybatis_config_file:  spring/spring-dataSource-config.xml

source_mapper_path:  elasticsearch/*.xml
source_entity_package: com.example.study.domain.elasticsearch


